### ISSUE TITLE
The game doesn't run

### ISSUE THREAD

**Issue by Fatihyuksek** [yncat/screamingstrike#10]
Hello,
The game doesn't run when I try to start play.exe. I am running Windows 10 64-bit with narrator. When I click play.exe, nothing happens.

**Comment by yncat** [comment]
That issue has been around since the first release. I really can't track it down, so I will have to use a different python to exe compiler. The next version will be compiled using pyinstaller.

**Comment by yncat** [comment]
Oh, if I could get the new version of Nuitka which has apparently been released yesterday, that is also an option. Still IDK.

**Comment by yncat** [comment]
2.03 was compiled by pyinstaller. I hope this solves the issue. I will once close this issue. Please open another one if the problem persists.
