### ISSUE TITLE
please add speech interrupt support to SAPI 5

### ISSUE THREAD

**Issue by Fatihyuksek** [yncat/screamingstrike#11]
Hello,
Can you please add speech interrupt to the game? What I mean by that is SAPI doesn't interrupt what it is spkeagin when I press any key. For example, when I press 2 to start an arcade game, it still reads the main menü and I am annoyed because I have to listen to it speaking. Try putting NVDA in sleep mode and play the game, press the arrow keys in the menus etc. You'll get what I mean. I am using narrator so I need this in order to play the game officiantly.
Thanks

**Comment by yncat** [comment]
Duplicate of #8

**Comment by yncat** [comment]
Implemented in the development branch.
